import sourceData from "../../content/sources/index.json";
import eventData from "../../content/events/index.json";
import conceptData from "../../content/concepts/index.json";
import organizationData from "../../content/organizations/index.json";
import familyData from "../../content/model-families/index.json";
import issueData from "../../content/issues/index.json";
import frontierData from "../../content/frontiers/index.json";
import pathData from "../../content/paths/index.json";
import modelReleaseData from "../../content/model-releases/index.json";
import modelProfileData from "../../content/model-profiles/index.json";
import {conceptSchema,eventSchema,modelFamilySchema,organizationSchema,sourceSchema,validateReferences} from "@/lib/schemas/content";
export type Source={id:string;title:string;url:string;publisher:string;year:number;tier?:1|2|3|4;verifiedAt:string;sourceType:"paper-or-technical-report"|"model-card"|"developer-docs"|"official-announcement"|"official-webpage"|"secondary-analysis";authorOrOrganization:string;publicationDate:string;verificationDate:string;classification:"primary"|"secondary";validationStatus:"linked-not-claim-verified"|"claim-verified"|"needs-review";supportsClaims:{id:string;claim:string}[]};
export type Event={id:string;slug:string;date:string;year:number;organization:string;type:"research"|"model"|"product"|"method"|"benchmark";title:string;titleEn:string;summary:string;importance:1|2|3;concepts:string[];conceptIds:string[];sourceId:string};
export type ConceptDocument={slug:string;titleKo:string;titleEn:string;summary:string;level:"입문"|"중급"|"심화";prerequisites:string[];next:string[];sourceIds:string[]};
export type IssueDocument={slug:string;titleKo:string;summary:string;fact:string;unknown:string;conceptIds:string[];sourceIds:string[]};
export type FrontierDocument={slug:string;titleKo:string;summary:string;shared:string;different:string;sourceIds:string[]};
export type LearningPathDocument={slug:string;titleKo:string;summary:string;conceptIds:string[];sourceIds:string[]};
export type OrganizationDocument={slug:string;titleKo:string;titleEn:string;summary:string;founded:string;sourceIds:string[]};
export type ModelFamily={slug:string;titleKo:string;titleEn:string;organizationSlug:string;summary:string;releaseSlugs:string[];sourceIds:string[]};
export type ModelRelease={familySlug:string;slug:string;date:string;title:string;titleEn:string;summary:string;sourceIds:string[];conceptIds:string[]};
export type ModelSpec={developer:string;released:string;modalities:string;context:string;variants:string;parameters:string;access:string;weights:string};
export type EditorialCoverage={outlet:string;title:string;url:string};
export type NotableEvent={date:string;title:string;description:string;sourceIds:string[]};
export type ModelProfile={familySlug:string;releaseSlug:string;summaryKo:string;spec:ModelSpec;features:string[];announcement:string[];reception:string;notableEvents:NotableEvent[];coverage:EditorialCoverage[];verifiedAt:string};
export const sources=sourceData as Source[];

export const conceptDocuments=conceptData as ConceptDocument[];
const conceptAlias:Record<string,string>={"attention":"attention","transformer":"transformer","rlhf":"rlhf","rag":"retrieval-augmented-generation","moe":"mixture-of-experts","context window":"context-window","contextual embeddings":"embedding","embedding":"embedding","autoregressive models":"pretraining","benchmark":"evaluation","code":"agents","compute":"scaling-laws","contrastive learning":"embedding","data":"data-quality","data quality":"data-quality","dialogue":"instruction-tuning","diffusion":"multimodality","distillation":"distillation","distributed training":"scaling-laws","efficiency":"inference-serving","evaluation":"evaluation","few-shot learning":"prompt-design","fine-tuning":"fine-tuning","foundation models":"pretraining","generation":"transformer","gqa":"attention","hallucination":"hallucination","image generation":"multimodality","in-context learning":"prompt-design","inference":"inference-serving","instruction tuning":"instruction-tuning","knowledge":"grounding","kv cache":"kv-cache","language models":"pretraining","long context":"long-context","mamba":"transformer","model family":"pretraining","multilingual":"pretraining","multimodality":"multimodality","open science":"data-quality","open weights":"alignment","preference optimization":"dpo","pretraining":"pretraining","programming":"agents","prompt":"prompt-design","quantization":"quantization","reasoning":"reasoning","reinforcement learning":"rlhf","rlaif":"rlaif","safety":"alignment","scaling":"scaling-laws","self reflection":"agent-memory","serving":"inference-serving","small language models":"small-language-models","speculative decoding":"speculative-decoding","speech":"multimodality","state space models":"transformer","structured output":"structured-output","tools":"agents","transfer learning":"fine-tuning","vision":"multimodality","vision language":"vision-language-models","audio":"multimodality","agents":"agents","alignment":"alignment"};
conceptAlias["rope"]="positional-encoding";
conceptAlias["positional encoding"]="positional-encoding";
conceptAlias["gqa"]="attention-variants";
conceptAlias["mamba"]="state-space-models";
conceptAlias["state space models"]="state-space-models";
conceptAlias["mla"]="mla";
conceptAlias["multi-head latent attention"]="mla";
conceptAlias["mcp"]="mcp";
conceptAlias["model context protocol"]="mcp";
export const events=(eventData as Omit<Event,"conceptIds">[]).map(event=>({...event,conceptIds:[...new Set(event.concepts.map(concept=>conceptAlias[concept.toLowerCase()]).filter((id):id is string=>Boolean(id)))]}));
export const issueDocuments=issueData as IssueDocument[];
export const frontierDocuments=frontierData as FrontierDocument[];
export const learningPathDocuments=pathData as LearningPathDocument[];
export const organizationDocuments=organizationData as OrganizationDocument[];
const familySeed=familyData as Omit<ModelFamily,"sourceIds">[];
const timelineModelReleases:ModelRelease[]=familySeed.flatMap(family=>family.releaseSlugs.flatMap(slug=>{const event=events.find(item=>item.slug===slug);return event?[{familySlug:family.slug,slug:event.slug,date:event.date,title:event.title,titleEn:event.titleEn,summary:event.summary,sourceIds:[event.sourceId],conceptIds:event.conceptIds}]:[]}));
export const modelReleases=[...timelineModelReleases,...modelReleaseData as ModelRelease[]];
export const modelProfiles=modelProfileData as ModelProfile[];
export const getModelProfile=(familySlug:string,releaseSlug:string)=>modelProfiles.find(profile=>profile.familySlug===familySlug&&profile.releaseSlug===releaseSlug);
export const modelFamilies=familySeed.map(family=>{const releases=modelReleases.filter(release=>release.familySlug===family.slug);return {...family,releaseSlugs:releases.map(release=>release.slug),sourceIds:[...new Set(releases.flatMap(release=>release.sourceIds))]};});
export const concepts=conceptDocuments.map(({slug,titleEn,summary,level})=>[slug,titleEn,summary,level] as const);
export const organizations=["OpenAI","Google DeepMind","Anthropic","Meta AI","Mistral AI","DeepSeek","Alibaba Cloud","Baidu","Cohere","Allen Institute for AI","Microsoft","Hugging Face"];
export const getSource=(id:string)=>sources.find(s=>s.id===id);
export const getEvent=(slug:string)=>events.find(e=>e.slug===slug);
sources.forEach(s=>sourceSchema.parse(s));
events.forEach(e=>eventSchema.parse({...e,type:{research:"\uC5F0\uAD6C",model:"\uBAA8\uB378",product:"\uC81C\uD488",method:"\uBC29\uBC95",benchmark:"\uBCA4\uCE58\uB9C8\uD06C"}[e.type]}));
organizationDocuments.forEach(o=>organizationSchema.parse(o));
modelFamilies.forEach(m=>modelFamilySchema.parse(m));
conceptDocuments.forEach(c=>conceptSchema.parse(c));
validateReferences(sources,events,conceptDocuments);
for(const event of events)if(!event.conceptIds.length)throw new Error(`${event.slug} has no normalized concept relationship`);
const sourceIds=new Set(sources.map(source=>source.id));
const conceptIds=new Set(conceptDocuments.map(concept=>concept.slug));
const organizationIds=new Set(organizationDocuments.map(organization=>organization.slug));
function validateDocument(slug:string,refs:{sourceIds:string[];conceptIds?:string[]}){for(const id of refs.sourceIds)if(!sourceIds.has(id))throw new Error(`${slug} references missing source ${id}`);for(const id of refs.conceptIds??[])if(!conceptIds.has(id))throw new Error(`${slug} references missing concept ${id}`)}
organizationDocuments.forEach(organization=>validateDocument(organization.slug,organization));
modelReleases.forEach(release=>validateDocument(`${release.familySlug}/${release.slug}`,release));
if(new Set(modelReleases.map(release=>`${release.familySlug}/${release.slug}`)).size!==modelReleases.length)throw new Error("Duplicate model release key");
if(new Set(modelProfiles.map(profile=>`${profile.familySlug}/${profile.releaseSlug}`)).size!==modelProfiles.length)throw new Error("Duplicate model profile key");
for(const release of modelReleases){const profile=getModelProfile(release.familySlug,release.slug);if(!profile)throw new Error(`Missing model profile for ${release.familySlug}/${release.slug}`);if(profile.features.length<1)throw new Error(`Insufficient model profile features for ${release.familySlug}/${release.slug}`);if(profile.notableEvents.length<1)throw new Error(`Missing notable event for ${release.familySlug}/${release.slug}`);for(const event of profile.notableEvents)validateDocument(`${release.familySlug}/${release.slug}/${event.title}`,{sourceIds:event.sourceIds});}
modelFamilies.forEach(family=>{validateDocument(family.slug,family);if(!organizationIds.has(family.organizationSlug))throw new Error(`${family.slug} references missing organization ${family.organizationSlug}`);for(const release of family.releaseSlugs)if(!modelReleases.some(item=>item.familySlug===family.slug&&item.slug===release))throw new Error(`${family.slug} references missing release ${release}`)});
issueDocuments.forEach(issue=>validateDocument(issue.slug,issue));
frontierDocuments.forEach(frontier=>validateDocument(frontier.slug,frontier));
learningPathDocuments.forEach(path=>validateDocument(path.slug,path));
