"use client";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { timelineLanes, timelineNodes, timelineRelations, timelineSubLanes } from "@/lib/timeline/data";
import { filterTimelineNodes } from "@/lib/timeline/filter";
import { layoutTimeline } from "@/lib/timeline/layout-lanes";
import { parseTimelineUrl, serializeTimelineUrl } from "@/lib/timeline/url-state";
import type { TimelineEntityType, TimelineUrlState } from "@/lib/timeline/types";

const trackOptions: [TimelineEntityType, string][] = [["model_release", "모델"], ["research", "연구"], ["method", "방법론"], ["product", "제품"], ["benchmark", "평가"], ["policy", "정책"], ["industry", "산업"]];
const entityLabels: Record<TimelineEntityType, string> = { model_release: "모델", research: "연구", method: "방법론", product: "제품", organization_event: "조직", policy: "정책", industry: "산업", benchmark: "평가" };
const fallback: TimelineUrlState = { view: "lineage", zoom: "overview", filters: { org: [], track: [], importance: 1, field: [] } };
function readState(): TimelineUrlState { if (typeof window === "undefined") return fallback; const parsed = parseTimelineUrl(new URLSearchParams(window.location.search)); return window.location.search ? parsed : { ...parsed, view: window.innerWidth <= 700 ? "list" : "lineage" as const }; }

export function TimelinePageShell() {
  const [state, setState] = useState<TimelineUrlState>(readState);
  const viewport = useRef<HTMLDivElement>(null);
  const nodes = useMemo(() => filterTimelineNodes(timelineNodes, state.filters), [state.filters]);
  const zoom = state.zoom === "detail" ? { level: 3 as const, start: "2022-01", pixels: 50 } : state.zoom === "era" ? { level: 2 as const, start: "2020-01", pixels: 30 } : { level: 1 as const, start: "2017-01", pixels: 18 };
  const layout = useMemo(() => layoutTimeline(nodes, timelineLanes, timelineSubLanes, state.filters.from ?? zoom.start, state.filters.to ?? "2026-08", zoom.pixels, zoom.level), [nodes, state.filters.from, state.filters.to, zoom.start, zoom.pixels, zoom.level]);
  const selected = timelineNodes.find(node => node.slug === state.selected);
  const related = useMemo(() => new Set(selected ? timelineRelations.filter(relation => relation.fromId === selected.id || relation.toId === selected.id).flatMap(relation => [relation.fromId, relation.toId]) : []), [selected]);
  const patch = (partial: Partial<TimelineUrlState>) => setState(current => ({ ...current, ...partial, filters: partial.filters ?? current.filters }));
  useEffect(() => { const query = serializeTimelineUrl(state); window.history.replaceState(null, "", window.location.pathname + (query ? "?" + query : "")); }, [state]);
  useEffect(() => { const node = layout.nodes.find(item => item.slug === state.selected); if (node && viewport.current) viewport.current.scrollTo({ left: Math.max(0, node.x - viewport.current.clientWidth / 2), behavior: "smooth" }); }, [layout, state.selected]);
  const toggleTrack = (track: TimelineEntityType) => patch({ filters: { ...state.filters, track: state.filters.track.includes(track) ? state.filters.track.filter(item => item !== track) : [...state.filters.track, track] } });
  return <section className="timelineShell" aria-label="AI history lineage map">
    <div className="timelineToolbar">
      <div className="viewSwitcher"><button type="button" aria-pressed={state.view === "lineage"} onClick={() => patch({ view: "lineage" })}>계보 지도</button><button type="button" aria-pressed={state.view === "list"} onClick={() => patch({ view: "list" })}>목록 보기</button></div>
      <label className="timelineSelect">조직<select value={state.filters.org[0] ?? ""} onChange={event => patch({ filters: { ...state.filters, org: event.target.value ? [event.target.value] : [] } })}><option value="">모든 조직</option>{timelineLanes.filter(lane => lane.type === "organization").map(lane => <option key={lane.id} value={lane.id}>{lane.titleKo}</option>)}</select></label>
      <label className="timelineSelect">중요도<select value={state.filters.importance} onChange={event => patch({ filters: { ...state.filters, importance: Number(event.target.value) as 1 | 2 | 3 } })}><option value="3">핵심</option><option value="2">주요 사건</option><option value="1">전체</option></select></label>
      <div className="zoomControls" aria-label="시간축 확대 수준"><button type="button" aria-pressed={state.zoom === "overview"} onClick={() => patch({ zoom: "overview" })}>전체</button><button type="button" aria-pressed={state.zoom === "era"} onClick={() => patch({ zoom: "era" })}>시대</button><button type="button" aria-pressed={state.zoom === "detail"} onClick={() => patch({ zoom: "detail" })}>상세</button></div>
    </div>
    <div className="filterChips">{trackOptions.map(([id, label]) => <button key={id} type="button" className={state.filters.track.includes(id) ? "active" : ""} aria-pressed={state.filters.track.includes(id)} onClick={() => toggleTrack(id)}>{label}</button>)}<button type="button" onClick={() => patch({ ...fallback, selected: undefined })}>초기화</button></div>
    {state.view === "lineage" ? <div ref={viewport} className="lineageViewport" tabIndex={0} aria-label="Horizontal timeline"><div className="lineageCanvas" style={{ width: layout.width, height: layout.height }}><svg className="lineageSvg" width={layout.width} height={layout.height} aria-hidden="true"><g className="yearGrid">{Array.from({ length: 10 }, (_, index) => 2017 + index).map((year, index) => { const x = 150 + index * (layout.width - 150) / 9; return <g key={year}><line x1={x} x2={x} y1="32" y2={layout.height} /><text x={x + 7} y="45">{year}</text></g>; })}</g>{Object.entries(layout.laneY).map(([id, y]) => <line key={id} className="laneLine" x1="150" x2={layout.width} y1={y} y2={y} />)}{timelineRelations.filter(relation => relation.visibleFromZoom <= zoom.level && layout.nodes.some(node => node.id === relation.fromId) && layout.nodes.some(node => node.id === relation.toId) && (!selected || (related.has(relation.fromId) && related.has(relation.toId)))).map(relation => { const from = layout.nodes.find(node => node.id === relation.fromId)!; const to = layout.nodes.find(node => node.id === relation.toId)!; const straight = relation.type === "next_release" && from.y === to.y; const path = straight ? "M" + from.x + "," + from.y + " L" + to.x + "," + to.y : "M" + from.x + "," + from.y + " C" + (from.x + 40) + "," + from.y + " " + (to.x - 40) + "," + to.y + " " + to.x + "," + to.y; return <path key={relation.id} className={"relation " + relation.type + (straight ? " straight" : "")} d={path} />; })}</svg><div className="laneLabels">{timelineLanes.filter(lane => layout.laneY[lane.id] !== undefined).map(lane => <span key={lane.id} style={{ top: layout.laneY[lane.id] + 8 }}>{lane.titleKo}</span>)}</div>{layout.nodes.map(node => <button key={node.id} type="button" className={"timelineNode kind-" + node.entityType + (selected?.id === node.id ? " selected" : "") + (selected && !related.has(node.id) ? " muted" : "")} style={{ left: node.x, top: node.y, "--label-shift": ["-34px", "12px", "-56px"][node.labelBand] } as CSSProperties} onClick={() => patch({ selected: node.slug })} title={node.titleKo + " " + node.primaryDate.value} aria-pressed={selected?.id === node.id}><i className="nodeDot" /><span className={node.labelVisible ? "nodeLabel" : "srOnly"}>{node.titleKo}</span></button>)}</div></div> : <TimelineList nodes={nodes} selected={state.selected} onSelect={slug => patch({ selected: slug })} />}
    <div className="timelineActions"><button type="button" onClick={() => viewport.current?.scrollBy({ left: -600, behavior: "smooth" })}>← 이전 시기</button><span>{nodes.length===timelineNodes.length?`${timelineNodes.length}개 사건`:`${nodes.length} / 전체 ${timelineNodes.length}개 사건`}</span><button type="button" onClick={() => viewport.current?.scrollBy({ left: 600, behavior: "smooth" })}>다음 시기 →</button></div>
    {selected && <Summary node={selected} onClose={() => patch({ selected: undefined })} />}
    <noscript><section className="noscriptTimeline"><p>Timeline list</p><ol>{timelineNodes.map(node => <li key={node.id}><a href={"/timeline/" + node.slug + "/"}>{node.primaryDate.value} - {node.titleKo}</a></li>)}</ol></section></noscript>
  </section>;
}
function TimelineList({ nodes, selected, onSelect }: { nodes: typeof timelineNodes; selected?: string; onSelect: (slug: string) => void }) { return <div className="timelineList">{nodes.map(node => <article key={node.id} className={selected === node.slug ? "selected" : ""}><time>{node.primaryDate.value}</time><div><span>{entityLabels[node.entityType]}</span><h2><button type="button" onClick={() => onSelect(node.slug)}>{node.titleKo}</button></h2><p>{node.summaryKo}</p><Link href={"/timeline/" + node.slug + "/"}>상세 보기 ↗</Link></div></article>)}</div>; }
function Summary({ node, onClose }: { node: typeof timelineNodes[number]; onClose: () => void }) { return <aside className="nodeSummary"><button className="closeSummary" type="button" onClick={onClose} aria-label="닫기">×</button><p>{node.primaryDate.value} · {entityLabels[node.entityType]}</p><h2>{node.titleKo}</h2><p className="en">{node.titleEn}</p><p>{node.summaryKo}</p><small>연결된 출처 {node.sourceIds.length}개</small><Link href={"/timeline/" + node.slug + "/"}>상세 페이지 열기 →</Link></aside>; }
